config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :statuses

    root 'statuses#index'
  end

  root 'index#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/status.rb
class Status < ApplicationRecord
  validates :label, presence: true, uniqueness: true
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
end

app/controllers/admin/statuses_controller.rb
class Admin::StatusesController < Admin::BaseController
  before_action :set_status, only: %i[show edit update destroy]

  def index
    @statuses = Status.all
  end

  def show
  end

  def new
    @status = Status.new
  end

  def edit
  end

  def create
    @status = Status.new(status_params)

    if @status.save
      redirect_to [:admin, @status], notice: 'Status was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @status.update(status_params)
      redirect_to [:admin, @status], notice: 'Status was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @status.destroy
    redirect_to admin_statuses_url, notice: 'Status was successfully destroyed.'
  end

  private

  def set_status
    @status = Status.find(params[:id])
  end

  def status_params
    params.require(:status).permit(:label)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController

  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/base/_error_messages.html.erb
<% if target.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% target.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/base/_sidebar.html.erb
<div id="sidebar">
  <div class="header">
    <h1>Piwam</h1>
    <a href="#" id="btn-hide-sidebar">
      <i class="fas fa-times"></i>
    </a>
  </div>

  <div class="body">
    <div class="menu">
      <h3>Configuration</h3>
      <ul>
        <li><%= link_to 'About', '#' %></li>
        <li><%= link_to 'Preferences', '#' %></li>
      </ul>

      <h3>Members</h3>
      <ul>
        <li><%= link_to 'Manage members', '#' %></li>
        <li><%= link_to 'Geographic location', '#' %></li>
        <li><%= link_to 'Trombinoscope', '#' %></li>
        <li><%= link_to 'Manage statuses', admin_statuses_path %></li>
      </ul>

      <h3>Contributions</h3>
      <ul>
        <li><%= link_to 'Manage contributions', '#' %></li>
        <li><%= link_to 'Contribution types', '#' %></li>
      </ul>

      <h3>Accounting</h3>
      <ul>
        <li><%= link_to 'Activities', '#' %></li>
        <li><%= link_to 'Accounts', '#' %></li>
        <li><%= link_to 'Expenses', '#' %></li>
        <li><%= link_to 'Incomes', '#' %></li>
        <li><%= link_to 'Balance sheet', '#' %></li>
      </ul>

      <h3>Features</h3>
      <ul>
        <li><%= link_to 'Sign out', '#' %></li>
        <li><%= link_to 'Export data', '#' %></li>
        <li><%= link_to 'Mailings', '#' %></li>
        <li><%= link_to 'Report a bug', '#' %></li>
        <li><%= link_to 'Installation', '#' %></li>
        <li><%= link_to 'Update', '#' %></li>
      </ul>
    </div>
  </div>
</div>

app/views/admin/statuses/_form.html.erb
<%= form_with(model: [:admin, status]) do |form| %>
  <%= render 'admin/base/error_messages', target: status %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/statuses/edit.html.erb
<h1>Editing status</h1>

<%= render 'form', status: @status %>

<br>

<div>
  <%= link_to 'Show this status', [:admin, @status] %> |
  <%= link_to 'Back to statuses', admin_statuses_path %>
</div>

app/views/admin/statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Status</h2>

<table id="statuses" class="table">
  <thead>
    <tr>
      <th><%= link_to 'Label', '#' %></th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @statuses.each do |status| %>
      <tr id="<%= dom_id status %>">
        <td><%= status.label %></td>
        <td class="has-text-centered"><%= link_to 'Show', [:admin, status] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New status', new_admin_status_path, class: 'button' %>

app/views/admin/statuses/new.html.erb
<h1>New status</h1>

<%= render 'form', status: @status %>

<br>

<div>
  <%= link_to 'Back to statuses', admin_statuses_path %>
</div>

app/views/admin/statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @status.label %>
</p>

<div>
  <%= link_to 'Edit this status', edit_admin_status_path(@status) %> |
  <%= link_to 'Back to statuses', admin_statuses_path %>

  <%= button_to 'Destroy this status', admin_status_path(@status), method: :delete %>
</div>

app/views/index/index.html.erb
<div class="welcome">
  <h1>Piwam</h1>

  <p>
    Welcome to Piwam, your simple and efficient association manager.<br>
    Start configuring your site from the administration console.
  </p>

  <p>
    <%= link_to "Let's get started!", admin_root_path, class: 'button' %>
  </p>
</div> 

app/views/layouts/admin/base.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piwam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'admin/base', 'data-turbo-track': 'reload' %>
    <script defer src="https://use.fontawesome.com/releases/v5.14.0/js/all.js"></script>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div id="container">
      <div id="header">
        <a href="#" id="btn-show-sidebar">
          <i class="fas fa-bars"></i>
        </a>
        <h1>Piwam</h1>
      </div>

      <div class="is-flex">
        <%= render 'sidebar' %>

        <div id="content">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Piwam</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', 'data-turbo-track': 'reload' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>